# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vista1_P3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #CDE8DF")
        self.centralwidget.setObjectName("centralwidget")
        self.listar_button = QtWidgets.QPushButton(self.centralwidget)
        self.listar_button.setGeometry(QtCore.QRect(670, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listar_button.setFont(font)
        self.listar_button.setStyleSheet("background-color: #B3C9C2; ")
        self.listar_button.setObjectName("listar_button")
        self.lote_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lote_input.setGeometry(QtCore.QRect(610, 190, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lote_input.setFont(font)
        self.lote_input.setStyleSheet("background-color: #BDD4CD;")
        self.lote_input.setText("")
        self.lote_input.setObjectName("lote_input")
        self.imgBarrio = QtWidgets.QLabel(self.centralwidget)
        self.imgBarrio.setGeometry(QtCore.QRect(20, 150, 541, 391))
        self.imgBarrio.setText("")
        self.imgBarrio.setPixmap(QtGui.QPixmap(":/Imagenesp/MapaBarrioEdit.png"))
        self.imgBarrio.setScaledContents(True)
        self.imgBarrio.setWordWrap(False)
        self.imgBarrio.setObjectName("imgBarrio")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(320, 50, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listar_button.setText(_translate("MainWindow", "Listar Todos"))
        self.lote_input.setPlaceholderText(_translate("MainWindow", "🔍 Buscar Lote o Dueño"))
        self.titulo.setText(_translate("MainWindow", "SISTEMA DE GESTIÓN DE LOTES"))

#from Imagenes import source
import Vista.Imagenes.source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
