# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabla.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FromTabla(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(819, 539)
        self.tablaLotes = QtWidgets.QTableWidget(Form)
        self.tablaLotes.setGeometry(QtCore.QRect(0, 0, 861, 581))
        self.tablaLotes.setAutoFillBackground(False)
        self.tablaLotes.setObjectName("tablaLotes")
        self.tablaLotes.setColumnCount(0)
        self.tablaLotes.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
